### ISSUE TITLE
Add appparticle to the tools in the Cocos2d-x website

### ISSUE THREAD

**Issue by rraallvv** [pierredavidbelanger/apparticle#9]
I'm using particles created with appparticle in my Cocos2d-x projects and wanted to suggest adding appparticle to the tools listed in the [Cocos2d-x website](http://www.cocos2d-x.org/hub). The reason is that there aren't free apps in the list with similar UI and features that ParticleDesigner, which happens to be a commercial app.

Regards, and keep up the good work ;-)

**Comment by pierredavidbelanger** [comment]
OMG, I am glad someone actually use this tool, I had almost forgot about it :)

I will indeed look at how I can submit my tool into the the Cocos2d hub, I guess it can be useful to someone else.

It's been a while since I have not updated the project, did you find any bug ? Do you have any feature request ? 

Maybe I can bump the version to 1.0 stable now :)

**Comment by pierredavidbelanger** [comment]
Here: http://www.cocos2d-x.org/hub/188

Thank you for the hint!

Also, you can tel me if something is missing from this tool, I will gladly take some time to polish it.

**Comment by rraallvv** [comment]
@pierredavidbelanger AppParticle is pretty easy to use and has a straight forward UI, maybe adding a button to reset the emitter or loading presets from those already built-in in the engine like CCParticleFire or CCParticleFireworks.

**Comment by pierredavidbelanger** [comment]
Interesting!

I like the idea of being able to choose a built in preset.
I should be relatively easy to implements too.

Maybe I can find a way to include (of fetch from the web) a collection of presets from other users too.
Do you happen to know if there is an open/free repository somewhere of user submitted emitters (ideally in the .plist format) ?

The reset button makes sense too.

A big thank you for your feedbacks!

**Comment by pierredavidbelanger** [comment]
If you want to contribute further to those ideas: see issues #10 and #11

**Comment by pierredavidbelanger** [comment]
I released a v0.4.1 that contains an Open preset menu to let you choose builtin Cocos2D emitters.

Sparkle (auto update) is broken since v0.3, but you can find the latest version here:
https://github.com/pierredavidbelanger/apparticle/releases
